name: Hegel
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
  pull_request:

env:
  REGISTRY: quay.io
  IMAGE: quay.io/${{ github.repository }}
  CGO_ENABLED: 0
  GO_VERSION: 1.19

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: Run tests
        run: go test -coverprofile=coverage.txt ./...

      - name: Upload coverage report (codcov.io)
        run: bash <(curl -s https://codecov.io/bash)

  integration:
    name: Test - Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: Run integration tests
        run: make test-integration

      - name: Upload coverage report (codcov.io)
        run: bash <(curl -s https://codecov.io/bash)

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: Build binaries
        run: make build

  e2e:
    name: Test - E2E
    runs-on: ubuntu-latest
    needs: [test, integration]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "${{ env.GO_VERSION }}"
          cache: true

      - name: Run end-to-end tests
        run: make test-e2e

      - name: Upload coverage report (codcov.io)
        run: bash <(curl -s https://codecov.io/bash)

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: [lint, build, test, e2e]
    steps:
      - uses: actions/checkout@v3

      - name: Login to quay.io
        uses: docker/login-action@v2
        if: ${{ startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/heads/v') }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        run: make image
